# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: bioc-release

warnings_are_errors: false

addons:
  apt:
    packages:
      - libudunits2-dev
      - libmagick++-dev
    sources:
      - ubuntu-toolchain-r-test

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

notifications:
  email:
    recipients:
      - bonhomme.vincent@gmail.com
    on_success: change
    on_failure: change

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
